name       : python-django
version    : 2.1.3
release    : 3
source     :
    - https://github.com/django/django/archive/2.1.3.tar.gz : c6f47e87426c324e206b7083bcdf99e0b91a992ba14cb91ded8f3a57cff8f4f1
license    : BSD-3-Clause
component  : programming.python
summary    : Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
description: |
    Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
rundeps    :
    - python3
    - python-pytz
build      : |
    %python3_setup
install    : |
    %python3_install
