name       : python-django
version    : 4.1.2
release    : 16
source     :
    - https://files.pythonhosted.org/packages/source/D/Django/Django-4.1.2.tar.gz : b8d843714810ab88d59344507d4447be8b2cf12a49031363b6eed9f1b9b2280f
homepage   : https://www.djangoproject.com
license    : BSD-3-Clause
component  : programming.python
summary    : A high-level Python web framework that encourages rapid development and clean, pragmatic design
description: |
    Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
rundeps    :
    - python-asgiref
    - python-pytz
    - python-sqlparse
build      : |
    %python3_setup
install    : |
    %python3_install
