name       : python-django
version    : 2.1.7
release    : 5
source     :
    - https://github.com/django/django/archive/2.1.7.tar.gz : c939a1c011c2079a3d5d67833a973a0e50602cd4407b24b998e6d232ddd8ae28
license    : BSD-3-Clause
component  : programming.python
summary    : Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
description: |
    Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
rundeps    :
    - python3
    - python-pytz
build      : |
    %python3_setup
install    : |
    %python3_install
