name       : python-django
version    : '2.2'
release    : 6
source     :
    - https://github.com/django/django/archive/2.2.tar.gz : 5d20b40362704c2bd0ec90e7c6a2d6457441e4bfc83794c2930d030af6c31f61
license    : BSD-3-Clause
component  : programming.python
summary    : Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
description: |
    Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
# python-sqlparse needed to check
#builddeps  :
#    - python-pytest
#    - python-pytz
#    - python-sqlparse
rundeps    :
    - python-pytz
    - python-sqlparse
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |     will comment it out once python-sqlparse is included in repo
#    %python3_test tests/runtests.py