name       : python-django
version    : 4.1.1
release    : 15
source     :
    - https://files.pythonhosted.org/packages/source/D/Django/Django-4.1.1.tar.gz : a153ffd5143bf26a877bfae2f4ec736ebd8924a46600ca089ad96b54a1d4e28e
homepage   : https://www.djangoproject.com
license    : BSD-3-Clause
component  : programming.python
summary    : A high-level Python web framework that encourages rapid development and clean, pragmatic design
description: |
    Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
rundeps    :
    - python-asgiref
    - python-pytz
    - python-sqlparse
build      : |
    %python3_setup
install    : |
    %python3_install
