name       : python-django
version    : 4.1.3
release    : 17
source     :
    - https://files.pythonhosted.org/packages/source/D/Django/Django-4.1.3.tar.gz : 678bbfc8604eb246ed54e2063f0765f13b321a50526bdc8cb1f943eda7fa31f1
homepage   : https://www.djangoproject.com
license    : BSD-3-Clause
component  : programming.python
summary    : A high-level Python web framework that encourages rapid development and clean, pragmatic design
description: |
    Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
rundeps    :
    - python-asgiref
    - python-pytz
    - python-sqlparse
build      : |
    %python3_setup
install    : |
    %python3_install
