name       : python-django
version    : 2.2.4
release    : 10
source     :
    - https://github.com/django/django/archive/2.2.4.tar.gz : 9298474f3157cfc576d97c532df459451ac3982a72c6e098dfe836778a29a91b
license    : BSD-3-Clause
component  : programming.python
summary    : Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
description: |
    Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
rundeps    :
    - python-pytz
    - python-sqlparse
build      : |
    %python3_setup
install    : |
    %python3_install
