name       : python-django
version    : 2.2.2
release    : 8
source     :
    - https://github.com/django/django/archive/2.2.2.tar.gz : 1d75d3ae1f6151642538fa65169fdb2ffccfbd0cc65b2d709c8915d7bcec1cde
license    : BSD-3-Clause
component  : programming.python
summary    : Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
description: |
    Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
rundeps    :
    - python-pytz
    - python-sqlparse
build      : |
    %python3_setup
install    : |
    %python3_install
