name       : python-django
version    : 2.2.3
release    : 9
source     :
    - https://github.com/django/django/archive/2.2.3.tar.gz : 7e31a5c35af2726b185e60c3e87513e5e8559c47582f4ebc32006bb761247876
license    : BSD-3-Clause
component  : programming.python
summary    : Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
description: |
    Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
rundeps    :
    - python-pytz
    - python-sqlparse
build      : |
    %python3_setup
install    : |
    %python3_install
