name       : python-django
version    : 2.1.5
release    : 4
source     :
    - https://github.com/django/django/archive/2.1.5.tar.gz : c73c2b391fa8f210bf6c77235fcc999562b627577bcfb40158c17afd0d3260da
license    : BSD-3-Clause
component  : programming.python
summary    : Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
description: |
    Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
rundeps    :
    - python3
    - python-pytz
build      : |
    %python3_setup
install    : |
    %python3_install
