name       : python-django
version    : 2.1.2
release    : 2
source     :
    - https://github.com/django/django/archive/2.1.2.tar.gz : 60b791ee60a2a959c9d7046f7604c6669217ee1c4a5b0c22a00974ccd705dbeb
license    : BSD-3-Clause
component  : programming.python
summary    : Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
description: |
    Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python3
    - python-pytz
    - python-setuptools
build      : |
    %python3_setup
install    : |
    %python3_install
