name       : python-django
version    : 2.2.6
release    : 11
source     :
    - https://github.com/django/django/archive/2.2.6.tar.gz : 1713e1712447e78c4599d182886a532fdffb11649d02273171dea925528fbf6b
homepage   : https://www.djangoproject.com
license    : BSD-3-Clause
component  : programming.python
summary    : Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
description: |
    Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
rundeps    :
    - python-pytz
    - python-sqlparse
build      : |
    %python3_setup
install    : |
    %python3_install
