name       : python-django
version    : 4.2.3
release    : 18
source     :
    - https://files.pythonhosted.org/packages/source/D/Django/Django-4.2.3.tar.gz : 45a747e1c5b3d6df1b141b1481e193b033fd1fdbda3ff52677dc81afdaacbaed
homepage   : https://www.djangoproject.com
license    : BSD-3-Clause
component  : programming.python
summary    : A high-level Python web framework that encourages rapid development and clean, pragmatic design
description: |
    Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.
rundeps    :
    - python-asgiref
    - python-pytz
    - python-sqlparse
build      : |
    %python3_setup
install    : |
    %python3_install
